//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace homeexam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class product_table
    {
        public string id { get; set; }
        [Required]
        [MaxLength(20)]
        public string product_name { get; set; }
        [Required]
        public Nullable<double> product_Quantity { get; set; }
        [Required]
        public int product_id { get; set; }
    
        public virtual buyertable buyertable { get; set; }
    }
}
